require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/expense_reports", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExpenseReport. As you add validations to ExpenseReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExpenseReport.create! valid_attributes
      get expense_reports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expense_report = ExpenseReport.create! valid_attributes
      get expense_report_url(expense_report)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expense_report_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      expense_report = ExpenseReport.create! valid_attributes
      get edit_expense_report_url(expense_report)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExpenseReport" do
        expect {
          post expense_reports_url, params: { expense_report: valid_attributes }
        }.to change(ExpenseReport, :count).by(1)
      end

      it "redirects to the created expense_report" do
        post expense_reports_url, params: { expense_report: valid_attributes }
        expect(response).to redirect_to(expense_report_url(ExpenseReport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExpenseReport" do
        expect {
          post expense_reports_url, params: { expense_report: invalid_attributes }
        }.to change(ExpenseReport, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post expense_reports_url, params: { expense_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested expense_report" do
        expense_report = ExpenseReport.create! valid_attributes
        patch expense_report_url(expense_report), params: { expense_report: new_attributes }
        expense_report.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the expense_report" do
        expense_report = ExpenseReport.create! valid_attributes
        patch expense_report_url(expense_report), params: { expense_report: new_attributes }
        expense_report.reload
        expect(response).to redirect_to(expense_report_url(expense_report))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        expense_report = ExpenseReport.create! valid_attributes
        patch expense_report_url(expense_report), params: { expense_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expense_report" do
      expense_report = ExpenseReport.create! valid_attributes
      expect {
        delete expense_report_url(expense_report)
      }.to change(ExpenseReport, :count).by(-1)
    end

    it "redirects to the expense_reports list" do
      expense_report = ExpenseReport.create! valid_attributes
      delete expense_report_url(expense_report)
      expect(response).to redirect_to(expense_reports_url)
    end
  end
end
